/*
17/11/2023
- Mais práticas envolvendo comandos DDL e DML do SQL.
*/

/*DDL*/

CREATE database PINHEIRO;

USE PINHEIRO;

DROP TABLE FORNECEDORES;

CREATE TABLE FORNECEDORES (
ID_FORNECEDOR INT auto_increment primary key,
RAZAO_SOCIAL VARCHAR(50) NOT NULL,
DATA_CADASTRO DATETIME,
CNPJ VARCHAR(15) NOT NULL
 

);

CREATE TABLE PRODUTOS (
ID_PRODUTO INT auto_increment primary key,
NOME_PRODUTO VARCHAR(50) NOT NULL,
VALIDADE DATETIME NOT NULL,
ID_FORNECEDOR INT,
foreign key (ID_FORNECEDOR) references FORNECEDORES (ID_FORNECEDOR)

);

DESC PRODUTOS;

/*DML*/
INSERT INTO FORNECEDORES (ID_FORNECEDOR,RAZAO_SOCIAL,DATA_CADASTRO,CNPJ)
VALUES (1, 'NESTLE', '2023-11-17', '123456789');

INSERT INTO FORNECEDORES (RAZAO_SOCIAL,DATA_CADASTRO,CNPJ)
VALUES ('GAROTO', NOW(), '123456789');

INSERT INTO FORNECEDORES (RAZAO_SOCIAL,DATA_CADASTRO,CNPJ)
VALUES ('TRÊS CORAÇÕES', NOW(), '123456789');

SELECT * FROM FORNECEDORES;
SELECT * FROM PRODUTOS;

INSERT INTO PRODUTOS (NOME_PRODUTO, VALIDADE, ID_FORNECEDOR)
VALUES 
('Dolce Gust', '2025-03-01', 3);

UPDATE PRODUTOS set ID_PRODUTO = 4 where ID_PRODUTO = 12


DROP TABLE PRODUTOS;
DESC PRODUTOS;
DESC FORNECEDORES;
DROP TABLE FORNECEDORES;

/*INNER JOIN*/

SELECT
    P.NOME_PRODUTO,
    DATE_FORMAT(P.VALIDADE, "%d/%m/%Y"),
    F.RAZAO_SOCIAL,
    F.CNPJ
    
FROM
    PRODUTOS AS P
    INNER JOIN FORNECEDORES AS F ON P.ID_FORNECEDOR = F.ID_FORNECEDOR;

/*LEFT JOIN*/

SELECT
    P.NOME_PRODUTO,
    DATE_FORMAT(P.VALIDADE, "%d/%m/%Y"),
    F.RAZAO_SOCIAL,
    F.CNPJ
    
FROM
    FORNECEDORES AS F
    LEFT JOIN FORNECEDORES AS P ON P.ID_FORNECEDOR = F.ID_FORNECEDOR;



